version: "3.8"

services:
  db-beers:
    image: mysql
    build: .
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beer
      MYSQL_USER: beer
      MYSQL_PASSWORD: beer
    restart: unless-stopped
    container_name: beers-db
    ports:
      - "8080:3306"